# Generated by Django 4.1.2 on 2022-10-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiProducto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='referecia',
            new_name='referencia',
        ),
    ]
